"""SCRP Phase 1 core plus the thin Phase 2 integration adapter."""

from .environment import SCRPEnvironment
from .models import (
    Container,
    EpisodeTerminatedError,
    EventKind,
    InstanceValidationError,
    InvalidActionError,
    Location,
    NoLegalRelocationError,
    Phase,
    SCRPConfig,
    SCRPError,
    SCRPInstance,
    SCRPState,
    Stack,
    StateInvariantError,
    StepLimitError,
    TransitionEvent,
    TransitionResult,
    is_guaranteed_restricted_feasible,
)
from .scenario import Scenario, ScenarioSampler
from .observation import (
    O1ObservationAdapter,
    O2ObservationAdapter,
    SCRPObservationConfig,
    SCRP_O2_FEATURE_NAMES,
    SCRP_O2_FEATURE_SCALE,
    O2_FEATURE_SCALE,
    SCRP_O2_MMAX,
    load_observation_config,
    save_observation_config,
)
from .rl_adapter import SCRPRLAdapter
from .datasets import (
    STATIC_INSTANCE_SCHEMA_VERSION,
    instance_from_record,
    instance_to_record,
    load_instance_json,
    merge_adjacent_batches,
    parse_ku_crptw,
    save_instance_json,
    validate_paper_instance,
)
from .formal_training import (
    BaselineRefreshRecord,
    BaseBalancedTrainingSampler,
    FormalTrainingConfig,
    KuTrainingInstanceProvider,
    SCRPFormalTrainer,
    TrainingSample,
    frozen_greedy_advantages,
    load_formal_training_config,
    make_node_padding_mask,
    make_scrp_policy,
    policy_state_sha256,
    save_formal_training_config,
)

__all__ = [
    "Container",
    "BaseBalancedTrainingSampler",
    "BaselineRefreshRecord",
    "EpisodeTerminatedError",
    "EventKind",
    "InstanceValidationError",
    "InvalidActionError",
    "FormalTrainingConfig",
    "Location",
    "KuTrainingInstanceProvider",
    "NoLegalRelocationError",
    "O1ObservationAdapter",
    "O2ObservationAdapter",
    "Phase",
    "SCRPConfig",
    "SCRPEnvironment",
    "SCRPError",
    "SCRPFormalTrainer",
    "SCRPInstance",
    "SCRPRLAdapter",
    "SCRPState",
    "SCRPObservationConfig",
    "SCRP_O2_FEATURE_NAMES",
    "SCRP_O2_FEATURE_SCALE",
    "O2_FEATURE_SCALE",
    "SCRP_O2_MMAX",
    "Scenario",
    "ScenarioSampler",
    "Stack",
    "STATIC_INSTANCE_SCHEMA_VERSION",
    "StateInvariantError",
    "StepLimitError",
    "TransitionEvent",
    "TransitionResult",
    "TrainingSample",
    "frozen_greedy_advantages",
    "is_guaranteed_restricted_feasible",
    "instance_from_record",
    "instance_to_record",
    "load_instance_json",
    "load_formal_training_config",
    "load_observation_config",
    "merge_adjacent_batches",
    "make_node_padding_mask",
    "make_scrp_policy",
    "policy_state_sha256",
    "parse_ku_crptw",
    "save_instance_json",
    "save_formal_training_config",
    "save_observation_config",
    "validate_paper_instance",
]
